name = "luna-ai-bot"
main = "index.ts"
compatibility_date = "2024-12-18"

workers_dev = true

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "SESSIONS"
id = "33277d761c894912a0e554e2b8b2a9a4"

[vars]
ADMIN_ID = "5989309344"
MAINTENANCE_MODE = "false"
WEBHOOK_URL = "https://luna-ai-bot.<YOUR_SUBDOMAIN>.workers.dev/webhook"

[env.production.vars]
ENVIRONMENT = "production"
ADMIN_ID = "5989309344"
MAINTENANCE_MODE = "false"
WEBHOOK_URL = "https://luna-ai-bot.<YOUR_SUBDOMAIN>.workers.dev/webhook"
